### ISSUE TITLE
[REJECTED] Crash when open some links

### ISSUE THREAD

**Issue by sergeevabc** [vovcacik/scrollmap#11]
Steps to reproduce.
1. Install Scrollmap.
2. Make sure ```browser.tabs.loadInBackground``` is ```true```.
3. Open [demo page][1].
4. Point at “dangerous link” there and choose to open it in a new (background) tab.

Expected: continue browsing with background tab being loaded as usual.
Actual: browser is crashed.

Tested with fresh profiles of [Pale Moon][2] 27.0.3 x64 and [Firefox][3] 50.1.0 x64.

[1]: http://txti.es/oyxpi
[2]: http://www.palemoon.org/
[3]: https://sourceforge.net/projects/pcxfirefox/

**Comment by vovcacik** [comment]
Hi, firefox 28 is last supported version. Due to some changes in Firefox four years ago I am and I will be unable to update this addon.
