### ISSUE TITLE
ScrollMap 0.9 compatibility with SeaMonkey

### ISSUE THREAD

**Issue by grahamperrin** [vovcacik/scrollmap#12]
If it's possible to update the description at <https://addons.mozilla.org/en-GB/firefox/addon/scrollmap/>, you might like to add that it's usable with SeaMonkey. 

Related: 

- http://forums.mozillazine.org/viewtopic.php?f=40&t=2834855&p=14777351#p14777351 

Thanks again!

**Comment by vovcacik** [comment]
That's interesting, thanks for letting me know!
