### ISSUE TITLE
Stylo incompatible with Scrollmap 0.9

### ISSUE THREAD

**Issue by grahamperrin** [vovcacik/scrollmap#13]
https://addons.mozilla.org/addon/scrollmap/versions/?page=1#version-0.9.1-signed.1-signed

Whilst testing [Stylo in Waterfox](https://github.com/MrAlex94/Waterfox/issues/332) I realised that Scrollmap does not work in normal pages. 

It continues to work in special pages such as `about:profiles`. 

## Workaround

1. `about:config`
2. boolean `layout.css.servo.enabled`
3. `false`

**Comment by vovcacik** [comment]
Hi, thanks for report. Waterfox is this addon's target application and as Firefox dropped support for XUL extensions (as this one) I am archiving this repo and I don't intend to maintain it.
