### ISSUE TITLE
Scrollmap 0.9 obscures sync and shutdown icons in the main menu of Firefox or Waterfox

### ISSUE THREAD

**Issue by grahamperrin** [vovcacik/scrollmap#14]
With Waterfox 56.0.1 on FreeBSD-CURRENT: 

![2017-12-28 18 04 35](https://user-images.githubusercontent.com/192271/34419092-d227e010-ebf9-11e7-94e0-8e5dfc9ffb3c.png)

The shutdown icon, I can do without. 

For the sync icon, I'll seek a workaround.

**Comment by grahamperrin** [comment]
Probably not an issue with SeaMonkey.

**Comment by grahamperrin** [comment]
> … For the sync icon, I'll seek a workaround. …

[Shifting the Firefox Sync icon to the left : FirefoxCSS](https://www.reddit.com/r/FirefoxCSS/comments/7zdxsc/shifting_the_firefox_sync_icon_to_the_left/)

**Comment by vovcacik** [comment]
Thanks for report, but this repo is being archived.
