### ISSUE TITLE
Scrollmap 0.9 disappears after loading www.waterfoxproject.org/blog/

### ISSUE THREAD

**Issue by grahamperrin** [vovcacik/scrollmap#15]
The map does appear at individual blog posts such as https://www.waterfoxproject.org/blog/waterfox-56.0-release-download 

![2018-02-21 20 12 18](https://user-images.githubusercontent.com/192271/36503322-a9949640-1744-11e8-91ea-b3f06473ed17.png)

At https://www.waterfoxproject.org/blog/ the map appears only whilst loading the page. Disappears when the load completes: 

![2018-02-21 20 18 47](https://user-images.githubusercontent.com/192271/36503332-b6de61b4-1744-11e8-8e16-e99d600217f8.png)

Any suggestions? 

TIA

----

Not a problem with Minimap Scroller 0.3.1 (below), but I prefer Scrollmap. 

![2018-02-21 20 09 58](https://user-images.githubusercontent.com/192271/36503390-df6a229e-1744-11e8-88b4-2d86150f51bb.png)

**Comment by grahamperrin** [comment]
A ten-second recording of the issue: 

- https://photos.app.goo.gl/tTEUMx7V67Lglje93

**Comment by vovcacik** [comment]
Hi, my guess would be that *something* is hiding scrollbar - it could be another addon, page rendering, css rule or something else. Quite likely the dark theme as you linked - MrAlex94/Waterfox#459. It would make perfect sense to me.

The scrollmap is written as enhancement of native scrollbar, that means the fancy scrollmap is **literally** the normal scrollbar but with some UI perks.
