### ISSUE TITLE
Why does scrollmap disappear on some pages?

### ISSUE THREAD

**Issue by piotrex** [vovcacik/scrollmap#2]
Steps to reproduce:
1. go to https://github.com/vovcacik/scrollmap
2. click on "chrome" folder
3. map has disappeared (at least for me)

BTW interesting addon

**Comment by vovcacik** [comment]
The page has no overflowing content, so scrollbar/scrollmap is expected to be hidden. Try to squeeze your Firefox window vertically and scrollmap will appear once some content overflows.

However if you want scrollmap to always appear, regardless content overflow create following file:

**`<Firefox profile>\chrome\userContent.css`**

``` css
html {
    overflow-y: scroll;
}
```

This is standard way to force vertical scrollbar to be always visible.

**Comment by piotrex** [comment]
> The page has no overflowing content, so scrollbar/scrollmap is expected to be hidden.

You're right! I didn't noticed it.
